name: success_stations
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  get_storage: ^2.0.2
  get: ^4.1.4
  google_fonts: ^2.1.0
  cupertino_icons: ^1.0.3
  google_sign_in: ^5.1.1
  http: ^0.13.3
  font_awesome_flutter: ^9.1.0
  im_stepper: ^0.1.3
  flutter_screenutil: ^5.0.0+2
  persistent_bottom_nav_bar: ^4.0.2
  flutter_login_facebook: ^1.0.1
  carousel_slider: ^4.0.0
  animated_widgets: ^1.1.0
  flutter_rating_bar: ^4.0.0
  google_maps_flutter: ^2.0.6
  shimmer: ^2.0.0
  firebase_crashlytics:
  url_launcher: ^6.0.9
  multiselect_formfield:
  multi_select_flutter: ^4.0.0
  flutter_multiselect:
  flutter_form_builder: ^7.1.0
  google_maps_place_picker: ^2.0.0-nullsafety.3
  dotted_border: ^2.0.0+1
  image_picker: ^0.8.3+2
  readmore: ^2.1.0
  dio: ^4.0.0
  flutter_shimmer: ^2.1.2
  flutter_html: ^3.0.0-alpha.2
  user_profile_avatar: ^0.1.0
  fluttertoast: ^8.0.8
  custom_info_window: ^1.0.1
  clippy_flutter: ^2.0.0-nullsafety.1
  geolocator: ^7.5.0
  web_socket_channel: ^2.1.0
  country_code_picker: ^2.0.2
  flutter_switch: ^0.3.2
  # go_sell_sdk_flutter: ^2.0.7
  intl_phone_field: ^3.0.1
  intl_phone_number_input: ^0.7.0+2
  socket_io_client: ^2.0.0-beta.4-nullsafety.0

  double_back_to_close_app: ^2.1.0
  flutter_datetime_picker: ^1.5.1
  flutter_launcher_icons: "^0.9.2"
  huawei_map: ^6.0.1+304
  material_color_gen: ^2.0.0




dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:


  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/images/saudia flags.png
    - assets/images/misar.png
    - assets/images/arab.png
    - assets/images/coppsule.png
    - assets/images/illustration@3x.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: STC Bold
      fonts:
        - asset: assets/fonts/stc.ttf

    #         style: italic
    - family: Poppins Regular
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
    - family: Cairo Regular
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf

    - family: Source_Sans_Pro
      fonts:
        - asset: assets/fonts/Source_Sans_Pro/SourceSansPro-Regular.ttf

    - family: andada
      fonts:
        - asset: assets/fonts/andada/AndadaPro-Regular.ttf
        # fonts:
        #   -  assets/fonts/stc.ttf

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
