export const PROFILE_IMAGE = 'PROFILE_IMAGE'
export const PROFILE_ADDRESS = 'PROFILE_ADDRESS'
export const REFRESH_FRIEND = 'REFRESH_FRIEND'
export const REFRESH_FAVORITE = 'REFRESH_FAVORITE'
export const LOGOUT = 'LOGOUT'

